export const LOGIN_START = "LOGIN_START";
export const LOGIN_OKAY = "LOGIN_OKAY";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FETCH_PHOTOS_START = "FETCH_PHOTOS_START";
export const FETCH_PHOTOS_OKAY = "FETCH_PHOTOS_OKAY";
export const FETCH_PHOTOS_FAIL = "FETCH_PHOTOS_FAIL";

export const FETCH_PHOTOS_SCROLL = "FETCH_PHOTOS_SCROLL";
export const FETCH_PHOTOS_SCROLL_OKAY = "FETCH_PHOTOS_SCROLL_OKAY";

export const SAVE_PHOTOS_START = "SAVE_PHOTOS_START";
export const SAVE_PHOTOS_OKAY = "SAVE_PHOTOS_OKAY";
export const SAVE_PHOTOS_FAIL = "SAVE_PHOTOS_FAIL";

export const FETCH_COLLECTION_START = "FETCH_COLLECTION_START";
export const FETCH_COLLECTION_OKAY = "FETCH_COLLECTION_OKAY";
export const FETCH_COLLECTION_FAIL = "FETCH_COLLECTION_FAIL";

export const LOGOUT = "LOGOUT";
